accessibility_model: /home/snajder/data/projects/tf_footprinting/nanopore_accessibility/trained_models/m5c_2021_08_01/r9.4_450bps.m5c.6mer.template.model
threads: 32

basedir: /scratch/snajder/nanopore_runs/run7

python: /home/snajder/miniconda3/envs/nanopore/bin/python
reference: /home/snajder/data/projects/tf_footprinting/reference/dmel-all-chromosome-r6.29.fasta

samtools: /g/stegle/snajder/software/opt/bin/samtools
nanopolish_acc: /home/snajder/data/code/nanopolish/nanopolish
nanopolish: /home/snajder/data/code/nanopolish_orig/nanopolish

minimap2: /g/stegle/snajder/software/opt/bin/minimap2
pycoQC: /home/snajder/miniconda3/envs/nanopore/bin/pycoQC

guppy_dir: /home/snajder/data/software/guppy/ont-guppy_4.4.1/

per_batch: 4
chroms: [2L,2R,3L,3R,4]
unique_samples: [sample]

scratch_dir: /scratch/snajder/tmp/
gpu_params: '--gpus 1'

mettypes: [cpg,gpc]
basecall_id: '000'

coords_file: /g/krebs/group_folder/smf_nanopore/analysis/acc_reference/run7/Context_met_call_V2_2021-06-11_GW_emb_2-4h_beads_DSP_test_Co19.pkl.gz