accessibility_model: /home/snajder/data/projects/tf_footprinting/nanopore_accessibility/trained_models/m5c_2021_08_01/r9.4_450bps.m5c.6mer.template.model
threads: 32

basedir: /g/krebs/group_folder/smf_nanopore/analysis/nanopore_runs/run8/emb2-4

python: /home/snajder/miniconda3/envs/nanopore/bin/python
reference: /home/snajder/data/projects/tf_footprinting/reference/dmel-all-chromosome-r6.29.fasta

Fast5_to_seq_summary: /home/snajder/miniconda3/envs/nanopore/bin/Fast5_to_seq_summary
samtools: /g/stegle/snajder/software/opt/bin/samtools
nanopolish_acc: /home/snajder/data/code/nanopolish/nanopolish
nanopolish: /home/snajder/data/code/nanopolish_orig/nanopolish

minimap2: /g/stegle/snajder/software/opt/bin/minimap2
pycoQC: /home/snajder/miniconda3/envs/nanopore/bin/pycoQC

guppy_dir: /g/krebs/group_folder/smf_nanopore/tools/guppy/ont-guppy

per_batch: 4
chroms: [2L,2R,3L,3R,4,X,Y,mitochondrion_genome]
unique_samples: [sample]

mapping_filter_params: -F 2304
filter_chroms: True

use_gpu_for_guppy: True
scratch_dir: /scratch/snajder/tmp/
jobid_env_var: SLURM_JOB_ID
gpu_params: '-p gpu --gres=gpu:1'

mettypes: [cpg,gpc]
basecall_id: '001'
keep_unfiltered_bam: True
min_read_q: 7

tabix_load_hook: module load tabix;
nanopolish_timp_conversion_script: /g/krebs/group_folder/smf_nanopore/tools/timp/nanopolish_timp_conversion_script.py
nanonome: /g/krebs/boulanger/Utilities/nanopolish_nanonome_timp_new_train/nanopolish

llr_threshold_nanopolish:
  - 1.0
  - 1.5
  - 2.0
llr_threshold_nanonome:
  - 1.0
  - 1.5
  - 2.0
llr_threshold_accessibility:
  - 1.0
  - 1.5
  - 2.0

custom_rules:
  - project_smfnanopore.rules

coords_file: /g/krebs/group_folder/smf_nanopore/analysis/acc_reference/run7/Context_met_call_V2_2021-06-11_GW_emb_2-4h_beads_DSP_test_Co19.pkl.gz