basedir: /homes/snajder/data/medulloblastoma/double_minute/

minimap2: /hps/nobackup/research/stegle/users/snajder/software/minimap2/minimap2
samtools: /hps/nobackup/research/stegle/users/snajder/software/samtools/bin/samtools
nanopolish: /hps/nobackup/research/stegle/users/snajder/software/nanopolish/nanopolish

python: /homes/snajder/miniconda3/envs/py37/bin/python

reference: /homes/snajder/data/medulloblastoma/from_assembly/assembly_tobias/double_minute/assembly.wtdbg2.fa

#per_batch: 15
chroms: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, X, Y, MT]
unique_samples: [dm]
basecall_id: '000'
mettypes: [cpg]
